### ISSUE TITLE
Add support for computer moves

### ISSUE THREAD

**Issue by bitpwr** [mandipandis/reversi#4]
Make new class, `Opponent` or `ComputerPlayer`

Add function
 `bestMove(board, tile)` - returns best position
  - for all free positions
   - if flippedTiles returns a list
     - clone board and apply list
     - put clone in a list
  
  for all in list of cloned board
   - get the board with highest value (bets board), return that position

Functions that might be needed
   
- board.value(tile) - high for corners, low for next to corners, count - count
- board.clone() - creates a new Board with same content
- board.setTiles(array)

**Comment by mandipandis** [comment]
solved
